%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

#Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 1047.64740
Camera1.fy: 1048.29680
Camera1.cx: 664.00941
Camera1.cy: 364.33427

# Distortion
Camera1.k1: -0.122296
Camera1.k2: 0.064661
Camera1.p1: -0.001169
Camera1.p2: -0.000828

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 1048.69203
Camera2.fy: 1049.45763
Camera2.cx: 689.43796
Camera2.cy: 365.52751

# Distortion
Camera2.k1: -0.124000
Camera2.k2: 0.067607
Camera2.p1: -0.001181
Camera2.p2: -0.000909
    
# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [ 1.0 ,   0.0104,   -0.0058,  0.3214,
         -0.0103, 1.0,      -0.0021, -0.0085,
          0.0058, 0.0023,    1.0001,  0.0039,
          0.0,    0.0,       0.0,     1.0]

# Camera resolution
Camera.width: 1366
Camera.height: 768

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 55.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 8

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
