%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

#Left Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 1047.6473989853982
Camera1.fy: 1048.2967629005661
Camera1.cx: 664.0094101264658 
Camera1.cy: 364.3342667335274

# Distortion
Camera1.k1: -0.12229559915133631 
Camera1.k2: 0.06466090928858183
Camera1.p1: -0.0011691434162538602 
Camera1.p2: -0.0008284494794836251

# Right Camera calibration and distortion parameters (OpenCV)
Camera2.fx: 1048.6920305526496 
Camera2.fy: 1049.457631031405 
Camera2.cx: 689.4379646033516 
Camera2.cy: 365.52751316101705

# Distortion
Camera2.k1: -0.12400062062732489 
Camera2.k2: 0.06760745639630127
Camera2.p1: -0.0011816633291866845 
Camera2.p2: -0.0009097959761755253
    
# Transformation matrix from right camera to left camera
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.99992893, 0.01039035,  -0.00584521, 0.32145947,
         -0.01040341, 0.99994344, -0.00220977, -0.00863324,
        0.00582192, 0.00227043, 0.99998048, 0.00399491,
        0.0,        0.0,        0.0,        1.0]

# Camera resolution
Camera.width: 1366
Camera.height: 768

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 55.0

IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [-0.00642587, -0.09059084,  0.99586746,  1.71398137,
          -0.99952934,  0.03045599, -0.00367902,  0.17077192,
          -0.02999685, -0.99542239, -0.09074391,  0.345256,
           0.,          0.,          0.,          1.]
# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (ADIS)

IMU.NoiseGyro: 0.01 
IMU.NoiseAcc: 0.1 
IMU.GyroWalk: 0.0001 
IMU.AccWalk: 0.001  
IMU.Frequency: 1000.0

# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 8

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
